name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  issues: write
  repository-projects: read
  contents: read

env:
  SOLUTION_FILE_PATH: .
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run Issue Bot
      uses: derjuulsn/todo-issue@main
      with:
        excludePattern: '^(include/)'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v4
      with:
        name: GuiClass
        path: |
          D:\a\GuiClass\GuiClass\x64\Release\GuiClass.exe
          D:\a\GuiClass\GuiClass\x64\Release\glfw3.dll
          D:\a\GuiClass\GuiClass\x64\Release\JetBrainsMonoNerdFont-Regular.ttf
